#! /bin/sh
set -e 
ucf /etc/processmonitor/processmonitor.conf.sample /etc/processmonitor/processmonitor.conf
ucf /etc/processmonitor/proc.list.sample /etc/processmonitor/proc.list
dpkg-statoverride --update --add openstack openstack 0755 /var/log/processmonitor
dpkg-statoverride --update --add openstack openstack 0755 /etc/processmonitor
dpkg-statoverride --update --add openstack openstack 0755 /opt/processmonitor/common.sh
dpkg-statoverride --update --add openstack openstack 0755 /opt/processmonitor/nova_compute_reboot_before.sh
dpkg-statoverride --update --add openstack openstack 0755 /opt/processmonitor/process_status_checker.sh
dpkg-statoverride --update --add openstack openstack 0755 /opt/processmonitor/processmonitor.sh
exit 0
