#! /bin/sh
set -e 
ucf --purge /etc/masakari/masakari.conf
dpkg-statoverride --remove /var/log/masakari
dpkg-statoverride --remove /opt/masakari/masakari.py
dpkg-statoverride --remove /opt/masakari/masakari_config.py
dpkg-statoverride --remove /opt/masakari/masakari_starter.py
dpkg-statoverride --remove /opt/masakari/masakari_util.py
dpkg-statoverride --remove /opt/masakari/masakari_worker.py
exit 0
