#! /bin/sh
set -e 
ucf /etc/masakari/masakari.conf.sample /etc/masakari/masakari.conf
dpkg-statoverride --update --add openstack openstack 0755 /var/log/masakari
dpkg-statoverride --update --add openstack openstack 0755 /opt/masakari/masakari.py
dpkg-statoverride --update --add openstack openstack 0644 /opt/masakari/masakari_config.py
dpkg-statoverride --update --add openstack openstack 0644 /opt/masakari/masakari_starter.py
dpkg-statoverride --update --add openstack openstack 0644 /opt/masakari/masakari_util.py
dpkg-statoverride --update --add openstack openstack 0644 /opt/masakari/masakari_worker.py
exit 0
