#! /bin/sh
set -e 
ucf /etc/masakari/masakari-controller.conf.sample /etc/masakari/masakari-controller.conf
LOG_DIR=/var/log/masakari
if [ -z "`dpkg-statoverride --list ${LOG_DIR}`" ] ; then dpkg-statoverride --update --add openstack openstack 0755 ${LOG_DIR} ; fi
dpkg-statoverride --update --add openstack openstack 0755 /opt/masakari/controller/masakari_controller.py
dpkg-statoverride --update --add openstack openstack 0644 /opt/masakari/controller/masakari_config.py
dpkg-statoverride --update --add openstack openstack 0644 /opt/masakari/controller/masakari_starter.py
dpkg-statoverride --update --add openstack openstack 0644 /opt/masakari/controller/masakari_util.py
dpkg-statoverride --update --add openstack openstack 0644 /opt/masakari/controller/masakari_worker.py
dpkg-statoverride --update --add openstack openstack 0644 /opt/masakari/controller/__init__.py
dpkg-statoverride --update --add openstack openstack 0644 /opt/masakari/db/api.py
dpkg-statoverride --update --add openstack openstack 0644 /opt/masakari/db/models.py
dpkg-statoverride --update --add openstack openstack 0644 /opt/masakari/db/__init__.py
exit 0
