#! /bin/sh
set -e 
ucf --purge /etc/instancemonitor/instancemonitor.conf
dpkg-statoverride --remove /var/log/instancemonitor
dpkg-statoverride --remove /opt/instancemonitor
dpkg-statoverride --remove /opt/instancemonitor/instancemonitor.py
dpkg-statoverride --remove /opt/instancemonitor/libvirt_eventfilter.py
dpkg-statoverride --remove /opt/instancemonitor/libvirt_eventfilter_table.py
dpkg-statoverride --remove /opt/instancemonitor/libvirt_callback.py
exit 0
