#!/bin/sh
set -e 
ucf /etc/masakari/masakari-instancemonitor.conf.sample /etc/masakari/masakari-instancemonitor.conf
LOG_DIR=/var/log/masakari
if [ -z "`dpkg-statoverride --list ${LOG_DIR}`" ] ; then dpkg-statoverride --update --add openstack openstack 0755 ${LOG_DIR}; fi
dpkg-statoverride --update --add openstack openstack 0755 /opt/masakari/masakari-instancemonitor/masakari-instancemonitor.py
dpkg-statoverride --update --add openstack openstack 0644 /opt/masakari/masakari-instancemonitor/libvirt_eventfilter.py
dpkg-statoverride --update --add openstack openstack 0644 /opt/masakari/masakari-instancemonitor/libvirt_eventfilter_table.py
dpkg-statoverride --update --add openstack openstack 0644 /opt/masakari/masakari-instancemonitor/libvirt_callback.py
exit 0
